"""Scan execution and persistence.

Two entry points:
    run_scan(domain)      — Pure: runs 7 checks, computes scores, returns results.
                            No side effects, no DB writes.
    persist_scan(...)     — Runs scan via run_scan(), saves to DB, returns public_token.
                            Used by web routes and batch API for shareable report URLs.

public_token is a 10-char URL-safe string generated by secrets.token_urlsafe(8).
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from typing import Any

from src.checks import (
    check_spf, check_dkim, check_dmarc, check_ptr,
    check_kisa_rbl, check_kisa_whitedomain, check_blacklists,
)
from src.db import save_scan
from src.models import CheckResult
from src.scorer import overall_score, naver_score, grade, naver_label


def run_scan(domain: str) -> tuple[list[CheckResult], dict[str, Any]]:
    """Run the full check pipeline and return (results, scores).

    This is a pure function — no DB writes, no side effects.
    """
    checks = [
        check_spf, check_dkim, check_dmarc, check_ptr,
        check_kisa_rbl, check_kisa_whitedomain, check_blacklists,
    ]

    with ThreadPoolExecutor() as pool:
        futures = [pool.submit(fn, domain) for fn in checks]
        results = [f.result() for f in futures]

    o_score = overall_score(results)
    n_score = naver_score(results)
    _, n_label = naver_label(n_score)
    scores = {
        "overall": o_score,
        "grade": grade(o_score),
        "naver": n_score,
        "naver_label": n_label,
    }
    return results, scores


def persist_scan(
    conn,
    *,
    domain: str,
    customer_id: int | None = None,
    results: list[CheckResult] | None = None,
    scores: dict[str, Any] | None = None,
) -> tuple[list[CheckResult], dict[str, Any], str]:
    """Run scan (if results not provided), persist to DB, return (results, scores, public_token).

    If results and scores are already available (e.g. from batch), pass them in
    to avoid re-scanning.
    """
    if results is None or scores is None:
        results, scores = run_scan(domain)

    checks_data = [
        {
            "name": r.name,
            "status": r.status,
            "score": r.score,
            "message_ko": r.message_ko,
            "detail_ko": r.detail_ko,
            "remediation_ko": r.remediation_ko,
            "raw": r.raw,
        }
        for r in results
    ]

    _, public_token = save_scan(
        conn,
        domain=domain,
        overall=scores["overall"],
        grade=scores["grade"],
        naver=scores["naver"],
        naver_label=scores["naver_label"],
        checks=checks_data,
        customer_id=customer_id,
    )

    return results, scores, public_token
